@startuml

actor User
participant "Mobile App" as App
box "Microservice" #LightBlue
participant "Repayment" as RepaymentService
end box
database "Loan" as DB

User -> App ++: Submit Repayment
App -> RepaymentService++ : POST /api/v1/loan-repayment
RepaymentService -> DB++ : Record Repayment Data
DB --> RepaymentService-- : Confirm Record
RepaymentService --> App-- : Return Data
App -> User-- : Display Repayment Success
@enduml